# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'Orbital' do

  use_frameworks! :linkage => :static

  # Pods for Orbital
  pod 'Firebase'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'







  target 'OrbitalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OrbitalUITests' do
    # Pods for testing
  end

end
use_frameworks! :linkage => :static