# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'Orbital' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orbital
  # pod 'Firebase/InAppMessaging'


  target 'OrbitalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OrbitalUITests' do
    # Pods for testing
  end

end
