# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'Orbital' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inherit! :search_paths
  # Pods for Orbital

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Firebase'

  target 'OrbitalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OrbitalUITests' do
    # Pods for testing
  end

end
