source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '10.25.0'
  pod 'Firebase/AppCheck', '10.25.0'
  pod 'Firebase/Auth', '10.25.0'
  pod 'Firebase/Core', '10.25.0'
  pod 'Firebase/Crashlytics', '10.25.0'
  pod 'Firebase/Database', '10.25.0'
  pod 'Firebase/DynamicLinks', '10.25.0'
  pod 'Firebase/Firestore', '10.25.0'
  pod 'Firebase/Functions', '10.25.0'
  pod 'Firebase/Messaging', '10.25.0'
  pod 'Firebase/RemoteConfig', '10.25.0'
  pod 'Firebase/Storage', '10.25.0'
  pod 'FirebaseInstallations'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
