# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Orbital' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orbital

  target 'OrbitalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OrbitalUITests' do
    # Pods for testing
  end

end

target 'unity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for unity

  target 'unityTests' do
    # Pods for testing
  end

end
